### ISSUE TITLE
Support prompt weighting similar to A1111

### ISSUE THREAD

**Issue by heurist-network** [heurist-network/miner-release#11]
## Problem Statement
A1111 WebUI and ComfyUI support weighted prompts like `A single dog with a (turtle shell:0.25) with (elephant:0.00) ears in the ((((art style of Greg Rutkowski))))` in which the () and numbers affect the attention of a key word/phrase. It can be used to emphasize a specific component in the prompt and make it more expressive. A tutorial of using prompt weights: https://www.andyhtu.com/post/prompt-weights-punctuations-how-to-use-it-in-automatic1111-stable-diffusion

This feature is not supported in native Diffusers pipelines. There is a community-made pipeline `lpw_stable_diffusion` and `lpw_stable_diffusion_xl` supporting this feature. 

Code: 
https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py
https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion_xl.py

Example Usage:
https://github.com/huggingface/diffusers/blob/main/examples/community/README.md#stable-diffusion-xl-long-weighted-prompt-pipeline

This will make the prompt format compatible with A1111 format that is commonly used in AI Art communities. This will also enable prompts longer than current length limit (77 tokens) to be processed without being truncated

## Acceptance Criteria
- LPW pipeline is integrated into the [benchmark script](https://github.com/heurist-network/lambda-diffusers/blob/main/scripts/benchmark.py)
- Benchmark script is executed and benchmark results are compared with vanilla SD(XL) pipeline to ensure LPW pipeline does not significantly increase the inference speed.
- If we confirm there's no significant performance impact, continue to integrate LPW pipeline in the SD and SDXL pipeline in our miner program
- Compare the outputs of a prompt with weighting annotations from LPW pipeline and from A1111 WebUI to ensure the results are equivalent. Use the same seed to test.

## Bounty
TBD

**Comment by EntroSanity** [comment]
Id like to give a try for this task.
