### ISSUE TITLE
ERROR: Miner ID for GPU 1 not found in .env. Exiting...

### ISSUE THREAD

**Issue by q172107875** [heurist-network/miner-release#38]
Starting in the Windows 10 environment
The configuration of. env is as follows: MINER-ID0=0x4B230fe0Bd7e53Abbjd8F39a84f4ca0b6C152521
The CUDA core has installed the driver
Error: Miner ID for GPU 1 not found in. env Exiting

**Comment by manishbyatroy** [comment]
Hi @q172107875,

Index's of gpu's start from 0. 
Are you running multi-gpu?
Can you please provide screenshot of `nvidia-smi`

**Comment by manishbyatroy** [comment]
The .env must follow a pattern like this :

MINER_ID_0=0x232323232332F
MINER_ID_1=0xd342c96e69251

**Comment by q172107875** [comment]
Thank you very much for resolving the previous issue and using 
nvidia-smi --query-gpu=uuid --format=csv
 to obtain UUID,
Then I encountered the following problem
![20240506191811](https://github.com/heurist-network/miner-release/assets/13548428/2b6d54ae-966f-4d73-806e-2c07fedbb50a)

**Comment by q172107875** [comment]
``
